import { IntelligenceCode } from "@/types/types";

export const questionnaire: {
  question: string;
  options: { answer: string; code: IntelligenceCode }[];
}[] = [
  {
    question: "Quand je suis libre, j'aime surtout…",
    options: [
      { answer: "Faire des expériences, résoudre des casse-têtes", code: "A" },
      { answer: "Lire, écrire, parler, écouter des histoires", code: "B" },
      { answer: "Dessiner, bricoler, imaginer des espaces", code: "C" },
      { answer: "Bouger, danser, jouer avec mon corps", code: "D" },
      {
        answer: "Écouter de la musique, chanter, jouer d'un instrument",
        code: "E",
      },
      { answer: "Être avec les autres, discuter, aider", code: "F" },
      { answer: "Être seul·e pour réfléchir ou rêver", code: "G" },
      { answer: "Me promener dehors, observer la nature", code: "H" },
    ],
  },
  {
    question: "À l'école, je préfère…",
    options: [
      { answer: "Les maths, les sciences, les problèmes", code: "A" },
      { answer: "Le français, l'histoire, les exposés", code: "B" },
      { answer: "L'art plastique, la géométrie", code: "C" },
      { answer: "L'EPS, le théâtre, les travaux manuels", code: "D" },
      { answer: "La musique, la poésie, les sons", code: "E" },
      { answer: "Les projets de groupe, les débats", code: "F" },
      { answer: "Les journaux de bord, les réflexions perso", code: "G" },
      { answer: "Les sorties nature, les expériences concrètes", code: "H" },
    ],
  },
  {
    question: "On dit souvent de moi que…",
    options: [
      { answer: "Je suis logique et organisé·e", code: "A" },
      { answer: "Je parle bien ou j'écris facilement", code: "B" },
      { answer: "J'ai une bonne mémoire visuelle", code: "C" },
      { answer: "Je suis agile ou doué·e en sport", code: "D" },
      { answer: "J'ai l'oreille musicale", code: "E" },
      { answer: "Je suis sociable et j'aide les autres", code: "F" },
      { answer: "Je me comprends bien moi-même", code: "G" },
      { answer: "J'adore les animaux ou les plantes", code: "H" },
    ],
  },
  {
    question: "Si je devais participer à un concours, je choisirais…",
    options: [
      { answer: "Un quiz de logique ou un défi scientifique", code: "A" },
      { answer: "Un concours d'éloquence ou d'écriture", code: "B" },
      { answer: "Un concours de dessin ou de maquettes", code: "C" },
      { answer: "Un parcours sportif ou un spectacle", code: "D" },
      { answer: "Un blind test ou un concours de chant", code: "E" },
      { answer: "Un projet collectif ou une simulation", code: "F" },
      { answer: "Un concours de réflexion personnelle", code: "G" },
      { answer: "Une exposition sur les insectes ou les plantes", code: "H" },
    ],
  },
  {
    question: "J'apprends mieux quand…",
    options: [
      { answer: "Je comprends les règles et je peux réfléchir", code: "A" },
      { answer: "Je lis ou j'explique à quelqu'un", code: "B" },
      { answer: "Je vois des images ou je fais des schémas", code: "C" },
      { answer: "Je fais les choses avec mon corps", code: "D" },
      { answer: "Je chante, je récite avec un rythme", code: "E" },
      { answer: "Je travaille avec d'autres ou j'en parle", code: "F" },
      { answer: "Je fais le lien avec ma vie ou mes émotions", code: "G" },
      { answer: "Je touche, observe, explore le réel", code: "H" },
    ],
  },
  {
    question: "Si je devais inventer quelque chose, ce serait…",
    options: [
      { answer: "Une machine ou une formule utile", code: "A" },
      { answer: "Une histoire ou un nouveau mot", code: "B" },
      { answer: "Un objet design ou un plan d'espace", code: "C" },
      { answer: "Une nouvelle chorégraphie ou un outil pratique", code: "D" },
      { answer: "Une chanson ou un son bizarre", code: "E" },
      { answer: "Une activité où chacun a un rôle", code: "F" },
      { answer: "Un journal intime illustré", code: "G" },
      { answer: "Un jardin ou une expérience avec des animaux", code: "H" },
    ],
  },
  {
    question: "En groupe, je suis celui/celle qui…",
    options: [
      { answer: "Organise la tâche et structure les étapes", code: "A" },
      { answer: "Reformule ce que tout le monde dit", code: "B" },
      { answer: "Dessine ou imagine la présentation", code: "C" },
      { answer: "Fait les manipulations ou déplace les objets", code: "D" },
      { answer: "Trouve la musique ou l'ambiance sonore", code: "E" },
      { answer: "Crée la cohésion, motive les autres", code: "F" },
      { answer: "Observe les tensions et reste discret·e", code: "G" },
      {
        answer: "Suggère des sorties dehors ou des exemples concrets",
        code: "H",
      },
    ],
  },
  {
    question: "Quand je regarde un film, je remarque surtout…",
    options: [
      { answer: "Le scénario et les retournements logiques", code: "A" },
      { answer: "Les dialogues et la narration", code: "B" },
      { answer: "L'esthétique et les décors", code: "C" },
      { answer: "Les mouvements des corps et les actions", code: "D" },
      { answer: "La musique et les sons", code: "E" },
      { answer: "Les relations entre les personnages", code: "F" },
      { answer: "L'évolution intérieure du héros", code: "G" },
      { answer: "Les environnements naturels", code: "H" },
    ],
  },
  {
    question: "Quand je suis en difficulté…",
    options: [
      { answer: "J'analyse la situation calmement", code: "A" },
      { answer: "J'en parle ou j'écris ce que je ressens", code: "B" },
      { answer: "Je dessine, je schématise ou j'observe", code: "C" },
      { answer: "Je me dépense ou je bouge pour me calmer", code: "D" },
      { answer: "J'écoute de la musique ou je chante", code: "E" },
      { answer: "Je demande de l'aide à quelqu'un", code: "F" },
      { answer: "Je réfléchis seul·e en silence", code: "G" },
      { answer: "Je vais dehors ou je m'occupe d'un animal", code: "H" },
    ],
  },
  {
    question: "Ce qui me vient naturellement, c'est…",
    options: [
      { answer: "Trouver la solution à un problème", code: "A" },
      { answer: "Raconter une blague ou une anecdote", code: "B" },
      { answer: "Visualiser des objets ou des plans dans ma tête", code: "C" },
      { answer: "Imiter, construire, expérimenter avec mes mains", code: "D" },
      { answer: "Reproduire une mélodie ou faire du rythme", code: "E" },
      { answer: "Lire les émotions des autres", code: "F" },
      { answer: "Comprendre ce que je ressens moi-même", code: "G" },
      { answer: "Identifier une plante ou un oiseau", code: "H" },
    ],
  },
  {
    question: "On me demande souvent de…",
    options: [
      { answer: "Résoudre un problème ou faire un calcul", code: "A" },
      { answer: "Lire à voix haute ou écrire un message", code: "B" },
      { answer: "Dessiner une carte, un plan ou un logo", code: "C" },
      {
        answer: "Aider à porter, construire ou monter quelque chose",
        code: "D",
      },
      {
        answer: "Trouver une chanson ou faire du bruit avec les objets",
        code: "E",
      },
      { answer: "Médiatiser une dispute ou écouter un ami", code: "F" },
      {
        answer: "Conseiller ou encourager quelqu'un à se comprendre",
        code: "G",
      },
      { answer: "Classer des objets, nettoyer, ranger la nature", code: "H" },
    ],
  },
  {
    question: "Si je devais apprendre un nouveau sujet…",
    options: [
      { answer: "Je veux en comprendre les règles et les causes", code: "A" },
      { answer: "Je veux lire des textes ou les expliquer", code: "B" },
      { answer: "Je veux voir des images ou des vidéos", code: "C" },
      { answer: "Je veux manipuler, tester ou m'exercer", code: "D" },
      { answer: "Je veux l'écouter ou le chanter", code: "E" },
      { answer: "Je veux l'apprendre à plusieurs", code: "F" },
      { answer: "Je veux me l'approprier dans mon vécu", code: "G" },
      { answer: "Je veux observer des éléments du réel", code: "H" },
    ],
  },
  {
    question: "À la maison, j'aime…",
    options: [
      {
        answer: "Faire des puzzles ou jouer à des jeux de stratégie",
        code: "A",
      },
      { answer: "Écrire, raconter, tenir un journal", code: "B" },
      { answer: "Créer des objets ou réorganiser ma chambre", code: "C" },
      { answer: "Bouger, danser, jouer avec des objets", code: "D" },
      { answer: "Écouter de la musique ou inventer des sons", code: "E" },
      { answer: "Appeler mes amis ou faire des jeux de groupe", code: "F" },
      { answer: "Me poser, réfléchir, méditer", code: "G" },
      { answer: "Observer mes plantes ou sortir avec mon chien", code: "H" },
    ],
  },
  {
    question: "Ce que je préfère dans une exposition ou un musée, c'est…",
    options: [
      { answer: "Les machines et explications scientifiques", code: "A" },
      { answer: "Les textes et documents anciens", code: "B" },
      { answer: "Les œuvres visuelles et les vidéos immersives", code: "C" },
      { answer: "Les dispositifs interactifs à manipuler", code: "D" },
      { answer: "Les sons, instruments ou installations musicales", code: "E" },
      { answer: "Les espaces partagés ou animés", code: "F" },
      { answer: "Les témoignages personnels", code: "G" },
      { answer: "Les animaux, fossiles ou plantes exposés", code: "H" },
    ],
  },
  {
    question: "Mon environnement idéal pour apprendre, c'est…",
    options: [
      { answer: "Calme, structuré, logique", code: "A" },
      { answer: "Avec un bon livre et un cahier", code: "B" },
      { answer: "Coloré, inspirant, visuel", code: "C" },
      { answer: "Spacieux, avec des objets à manipuler", code: "D" },
      { answer: "Musical ou rythmé", code: "E" },
      { answer: "En groupe, avec du dialogue", code: "F" },
      { answer: "Isolé et confortable", code: "G" },
      { answer: "En plein air ou proche de la nature", code: "H" },
    ],
  },
];
